
development:
  adapter: postgresql
  encoding: utf8
  database: memrybook_development
  pool: 5
  username: sowrov
  password: password

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: _test
  pool: 5
  username: sowrov
  password: password