
development:
  adapter: postgresql
  encoding: utf8
  database: memrybook_development
  pool: 5
  username: jacobtho
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: _test
  pool: 5
  username: jacobtho
  password: